routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false]);
Route::get('/', 'HomeController@index')->name('home');
Route::get('/start', 'HomeController@start')->name('start');
Route::resource('level', 'LevelController', ['only' => ['show']]);
Route::resource('exercise', 'ExerciseController', ['only' => ['show']]);

Route::prefix('admin')->middleware('auth:web')->group(function () {
    Route::resource('level', 'LevelController', ['except' => ['show']]);
    Route::prefix('level/{level}')->group(function () {
        Route::resource('exercise', 'ExerciseController', ['except' => ['show']]);
        Route::prefix('exercise/{exercise}')->group(function () {
            Route::resource('question', 'QuestionController');
        });
    });
});

app/Question.php
<?php

namespace App;

use Spatie\EloquentSortable\Sortable;
use Spatie\EloquentSortable\SortableTrait;
use Illuminate\Database\Eloquent\Model;

class Question extends Model implements Sortable
{
    use SortableTrait;

    public $sortable = [
        'order_column_name' => 'order',
        'sort_when_creating' => true,
    ];

    protected $guarded = ['id'];

    public function getPossibleAnswerAttribute($value)
    {
        return json_decode($value);
    }

    public function getPossibleAnswerStringAttribute()
    {
        return implode(' ', $this->possible_answer);
    }

    public function getCorrectAnswerAttribute($value)
    {
        return json_decode($value);
    }

    public function getCorrectAnswerStringAttribute()
    {
        $string = [];
        foreach ($this->correct_answer as $row) {
            $string[] = $row->el;
        }
        return implode(' ', $string);
    }

    public function exercise()
    {
        return $this->belongsTo(Exercise::class);
    }

    public function scopeByOrder($query, $order)
    {
        return $query->where('order', $order);
    }
}

app/Http/Controllers/QuestionController.php
<?php

namespace App\Http\Controllers;

use App\Level;
use App\Question;
use App\Http\Requests\RequestQuestion;
use App\Exercise;

class QuestionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Support\Facades\View
     */
    public function index(Level $level, Exercise $exercise)
    {
        $questions = Question::with('exercise')->orderBy('exercise_id', 'desc')->orderBy('order')->get();
        return view('question.index', compact('level', 'exercise', 'questions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Support\Facades\View
     */
    public function create(Level $level, Exercise $exercise)
    {
        $levels = Level::with('exercises')->get();
        return view('question.create', compact('level', 'exercise', 'levels'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\RequestQuestion  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Level $level, Exercise $exercise, RequestQuestion $request)
    {
        $inputs = $request->all();
        $inputs['possible_answer'] = json_encode(explode(' ', $inputs['possible_answer']));
        //$inputs['order'] = Question::where('exercise_id', $exercise->id)->max('order') + 1;
        $question = new Question($inputs);
        $question->save();
        return redirect()->route('question.index', [$level->id, $exercise->id])->with(['msg-success' => 'Question créé.']);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Question  $question
     * @return \Illuminate\Support\Facades\View
     */
    public function show(Level $level, Exercise $exercise, Question $question)
    {
        return view('question.edit', compact('level', 'exercise', 'question'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Question  $question
     * @return \Illuminate\Support\Facades\View
     */
    public function edit(Level $level, Exercise $exercise, Question $question)
    {
        $levels = Level::with('exercises')->get();
        return view('question.edit', compact('level', 'exercise', 'question', 'levels'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\RequestQuestion  $request
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function update(Level $level, Exercise $exercise, RequestQuestion $request, Question $question)
    {
        $inputs = $request->all();
        $inputs['possible_answer'] = json_encode(explode(' ', $inputs['possible_answer']));
        $question->update($inputs);
        return redirect()->route('question.index', [$level->id, $exercise->id])->with(['msg-success' => 'Question mis à jour.']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function destroy(Level $level, Exercise $exercise, Question $question)
    {
        $question->delete();
        return redirect()->route('question.index', [$level->id, $exercise->id])->with(['msg-success' => 'Question supprimé.']);
    }

    public function apiGetQuestion(Question $question)
    {
        return response()->json($question);
    }
}

resources/views/question/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <form id="question-form" method="POST" action="{{ route('question.store', [$level->id, $exercise->id]) }}" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group">
                            <label for="question">Question</label>
                            <textarea class="form-control" name="question" id="question"></textarea>
                        </div>
                        <div class="form-group">
                            <label for="exercise_id">Exercise</label>
                            <select class="form-control" name="exercise_id" id="exercise_id">
                                <option value="">----</option>
                                @foreach($levels as $level)
                                    <optgroup label="{{ $level->name }}">
                                        @foreach ($level->exercises as $row)
                                            <option value="{{ $row->id }}" {{ $row->id === $exercise->id ? 'selected="selected"' : ''}}>{{ $row->name }}</option>
                                        @endforeach
                                    </optgroup>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group">
                            <label for="correct_answer">La bonne réponse</label>
                            <input type="text" class="form-control" id="correct_answer" name="correct_answer" value="">
                            <div class="card">
                                <div class="card-body" id="answer">
                                    
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="possible_answer">Les réponses possibles</label>
                            <input type="text" class="form-control" id="possible_answer" name="possible_answer" value="">
                            <div class="card">
                                <div class="card-body" id="possible-answer">
                                    
                                </div>
                            </div>
                        </div>

                        <button type="submit" class="btn btn-primary float-right">Enregistrer</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('script')
    <script>
        (function(){
            $('#answer').on('click', '.badge', function(){
                $(this).toggleClass('badge-success badge-secondary')
            })
            $('#correct_answer').change(function(){
                $('#answer').html('')
                const correctAnswer = $(this).val().split(' ')
                $.each(correctAnswer, function(i, v){
                    $('#answer').append('<span data-answer="'+v+'" class="badge badge-secondary">'+v+'</span>')
                })
            })
            $('#possible_answer').change(function(){
                $('#possible-answer').html('')
                const possibleAnswer = $(this).val().split(' ')
                $.each(possibleAnswer, function(i, v){
                    $('#possible-answer').append('<span class="badge badge-secondary">'+v+'</span>')
                })
            })
            $('#question-form').submit(function(){
                let data = []
                $('#answer .badge').each(function(i, el){
                    data.push({
                        el: $(el).data('answer'),
                        inserted: $(el).hasClass('badge-success')
                    })
                })

                $('#correct_answer').val(JSON.stringify(data))
            })
        })()
    </script>
@endsection

resources/views/question/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <form id="question-form" method="POST" action="{{ route('question.update', [$level->id, $exercise->id, $question->id]) }}" enctype="multipart/form-data">
                        @csrf
                        @method('patch')
                        <div class="form-group">
                            <label for="question">Question</label>
                            <textarea class="form-control" name="question" id="question">{!! $question->question !!}</textarea>
                        </div>
                        <div class="form-group">
                            <label for="exercise_id">Exercise</label>
                            <select class="form-control" name="exercise_id" id="exercise_id">
                                <option value="">----</option>
                                @foreach($levels as $level)
                                    <optgroup label="{{ $level->name }}">
                                        @foreach ($level->exercises as $row)
                                            <option value="{{ $row->id }}" {{ $question->exercise_id === $row->id ? 'selected="selected"' : ''}}>{{ $row->name }}</option>
                                        @endforeach
                                    </optgroup>
                                @endforeach
                            </select>
                        </div>
                        
                        <div class="form-group">
                            <label for="correct_answer">La bonne réponse</label>
                            <input type="text" class="form-control" id="correct_answer" name="correct_answer" value="{{ $question->correct_answer_string }}">
                            <div class="card">
                                <div class="card-body" id="answer">
                                    @foreach($question->correct_answer as $tag)
                                    <span data-answer="{{ $tag->el }}" class="badge {{ $tag->inserted ? 'badge-success' : 'badge-secondary' }}">{{ $tag->el }}</span>
                                    @endforeach
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="possible_answer">Les réponses possibles</label>
                            <input type="text" class="form-control" id="possible_answer" name="possible_answer" value="{{ $question->possible_answer_string }}">
                            <div class="card">
                                <div class="card-body" id="possible-answer">
                                    @foreach($question->possible_answer as $tag)
                                    <span class="badge badge-secondary">{{ $tag }}</span>
                                    @endforeach
                                </div>
                            </div>
                        </div>

                        <button type="submit" class="btn btn-primary float-right">Enregistrer</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('script')
    <script>
        (function(){
            $('#answer').on('click', '.badge', function(){
                $(this).toggleClass('badge-success badge-secondary')
            })
            $('#correct_answer').change(function(){
                $('#answer').html('')
                const correctAnswer = $(this).val().split(' ')
                $.each(correctAnswer, function(i, v){
                    $('#answer').append('<span data-answer="'+v+'" class="badge badge-secondary">'+v+'</span>')
                })
            })
            $('#possible_answer').change(function(){
                $('#possible-answer').html('')
                const possibleAnswer = $(this).val().split(' ')
                $.each(possibleAnswer, function(i, v){
                    $('#possible-answer').append('<span class="badge badge-secondary">'+v+'</span>')
                })
            })
            $('#question-form').submit(function(){
                let data = []
                $('#answer .badge').each(function(i, el){
                    data.push({
                        el: $(el).data('answer'),
                        inserted: $(el).hasClass('badge-success')
                    })
                })
                $('#correct_answer').val(JSON.stringify(data))
            })
        })()
    </script>
@endsection

resources/views/question/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12 mb-2">
            <a class="btn btn-primary float-right" href="{{route('question.create', [$level->id, $exercise->id])}}" role="button">Nouveau</a>
        </div>
        <div class="col-md-12">
            <table class="table table-light table-striped">
                <thead class="thead-dark">
                    <tr>
                        <th>Order</th>
                        <th>Question</th>
                        <th>Exercise</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($questions as $question)
                    <tr>
                        <td class="align-middle">{{$question->order}}</td>
                        <td class="align-middle"><pre class="mb-0">{!!$question->question!!}</pre></td>
                        <td class="align-middle">{{$question->exercise ? $question->exercise->name : ''}}</td>
                        <td class="text-right align-middle">
                            <a class="edit-model" href="{{ route('question.edit', [$level->id, $exercise->id, $question->id]) }}"><i class="fas fa-edit"></i></a>
                            <form class="delete-model-form" method="POST" action="{{ route('question.destroy', [$level->id, $exercise->id, $question->id]) }}">
                                @csrf
                                @method('DELETE')
                                <i onclick="deleteModel(event)" class="fas fa-trash-alt delete-model"></i>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection

resources/views/question/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <img src="{{asset('storage/'.$exercise->image)}}" class="img-thumbnail" alt="{{$exercise->name}}">
                    <div class="form-group">
                        <label for="name">Nom</label>
                        <input type="text" class="form-control" name="name" id="name" value="{{ $exercise->name }}">
                    </div>
                    <div class="form-group">
                        <label for="description">Description</label>
                        <textarea class="form-control" name="description" id="description">{{ $exercise->description }}</textarea>
                    </div>
                    <div class="form-group">
                        <label for="level_id">Niveau</label>
                        <select class="form-control" name="level_id" id="level_id">
                            <option value="">----</option>
                            @foreach($levels as $level)
                                <option value="{{ $level->id }}" {{ $exercise->level_id === $level->id ? 'selected="selected"' : '' }} >{{ $level->name }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-check">
                        <label class="form-check-label">
                            <input type="checkbox" class="form-check-input" name="chrono" id="chrono" value="1" {{ $exercise->chrono ? 'checked="checked"' : '' }} >
                            Chrono
                        </label>
                    </div>
                    <div class="form-check">
                        <label class="form-check-label">
                            <input type="checkbox" class="form-check-input" name="active" id="active" value="1" {{ $exercise->active ? 'checked="checked"' : '' }} >
                            Active
                        </label>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection