routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false]);
Route::get('/', 'HomeController@index')->name('home');
Route::get('/start', 'HomeController@start')->name('start');
Route::resource('level', 'LevelController', ['only' => ['show']]);
Route::resource('exercise', 'ExerciseController', ['only' => ['show']]);

Route::prefix('admin')->middleware('auth:web')->group(function () {
    Route::resource('level', 'LevelController', ['except' => ['show']]);
    Route::prefix('level/{level}')->group(function () {
        Route::resource('exercise', 'ExerciseController', ['except' => ['show']]);
        Route::prefix('exercise/{exercise}')->group(function () {
            Route::resource('question', 'QuestionController');
        });
    });
});

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        @foreach($levels as $level)
        <div class="col-md-4">
            <div class="card level">
                <div class="card-body">
                    <p>{{ $level->name }}</p>
                    <a href="{{route('level.show', $level->id)}}" class="btn btn-primary">Choisir</a>
                </div>
            </div>
        </div>
        @endforeach
    </div>
</div>
@endsection

resources/views/start.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <question-component exercise_id="{{4}}"></question-component>
</div>
@endsection