routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false]);
Route::get('/', 'HomeController@index')->name('home');
Route::get('/start', 'HomeController@start')->name('start');
Route::resource('level', 'LevelController', ['only' => ['show']]);
Route::resource('exercise', 'ExerciseController', ['only' => ['show']]);

Route::prefix('admin')->middleware('auth:web')->group(function () {
    Route::resource('level', 'LevelController', ['except' => ['show']]);
    Route::prefix('level/{level}')->group(function () {
        Route::resource('exercise', 'ExerciseController', ['except' => ['show']]);
        Route::prefix('exercise/{exercise}')->group(function () {
            Route::resource('question', 'QuestionController');
        });
    });
});

app/Exercise.php
<?php

namespace App;

use App\Level;
use App\Question;
use Illuminate\Database\Eloquent\Model;

class Exercise extends Model
{
    protected $guarded = ['id'];

    public function level()
    {
        return $this->belongsTo(Level::class);
    }

    public function questions()
    {
        return $this->hasMany(Question::class);
    }
}

app/Http/Controllers/ExerciseController.php
<?php

namespace App\Http\Controllers;

use App\Level;
use App\Exercise;
use App\Question;
use App\Http\Requests\RequestExercise;

class ExerciseController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Support\Facades\View
     */
    public function index(Level $level)
    {
        $exercises = Exercise::with(['questions', 'level'])->get();
        return view('exercise.index', compact('level', 'exercises'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Support\Facades\View
     */
    public function create(Level $level)
    {
        $levels = Level::all();
        return view('exercise.create', compact('level', 'levels'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\RequestExercise  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Level $level, RequestExercise $request)
    {
        $values = $request->all();
        $values['image'] = $request->hasFile('image') ? $request->file('image')->store('exercises', 'public') : null;
        $exercise = new Exercise($values);
        $exercise->save();
        return redirect()->route('exercise.index', $level->id)->with(['msg-success' => 'Exercise créé.']);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Exercise  $exercise
     * @return \Illuminate\Support\Facades\View
     */
    public function show(Level $level, Exercise $exercise)
    {
        return view('exercise.show', compact('exercise', 'level'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Exercise  $exercise
     * @return \Illuminate\Support\Facades\View
     */
    public function edit(Level $level, Exercise $exercise)
    {
        $levels = Level::all();
        return view('exercise.edit', compact('level', 'levels', 'exercise'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\RequestExercise  $request
     * @param  \App\Exercise  $exercise
     * @return \Illuminate\Http\Response
     */
    public function update(Level $level, RequestExercise $request, Exercise $exercise)
    {
        $values = $request->all();
        if ($request->hasFile('img')) {
            $values['image'] = $request->file('img')->store('exercises', 'public');
        }
        $values['active'] = isset($request['active']) ?? false;
        $values['chrono'] = isset($request['chrono']) ?? false;
        $exercise->update($values);
        return redirect()->route('exercise.index', $level->id)->with(['msg-success' => 'Exercise mis à jour.']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Exercise  $exercise
     * @return \Illuminate\Http\Response
     */
    public function destroy(Level $level, Exercise $exercise)
    {
        $exercise->delete();
        return redirect()->route('exercise.index', $level->id)->with(['msg-success' => 'Exercise supprimé.']);
    }

    public function apiGetQuestionCount(Exercise $exercise)
    {
        return response()->json($exercise->questions()->count());
    }

    public function apiGetQuestion(Exercise $exercise, $order)
    {
        $question = $exercise->questions()->byOrder($order)->first();
        return response()->json($question);
    }
}

resources/views/exercise/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <form method="POST" action="{{ route('exercise.store', [$level->id]) }}" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group">
                            <label for="image">Image</label>
                            <input class="form-control" type="file" name="image" id="image">
                        </div>
                        <div class="form-group">
                            <label for="name">Nom</label>
                            <input type="text" class="form-control" name="name" id="name">
                        </div>
                        <div class="form-group">
                            <label for="description">Description</label>
                            <textarea class="form-control" name="description" id="description"></textarea>
                        </div>
                        <div class="form-group">
                            <label for="level_id">Niveau</label>
                            <select class="form-control" name="level_id" id="level_id">
                                <option value="">----</option>
                                @foreach($levels as $row)
                                    <option value="{{ $row->id }}" {{ $row->id === $level->id ? 'selected="selected"' : '' }} >{{ $row->name }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-check">
                            <label class="form-check-label">
                                <input type="checkbox" class="form-check-input" name="active" id="active" value="1" checked>
                                Active
                            </label>
                        </div>
                        
                        <button type="submit" class="btn btn-primary float-right">Enregistrer</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/exercise/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <form method="POST" action="{{ route('exercise.update', [$level->id, $exercise->id]) }}">
                        @csrf
                        @method('PATCH')
                        <img src="{{asset('storage/'.$exercise->image)}}" class="img-thumbnail" alt="{{$exercise->name}}">
                        <div class="form-group">
                            <label for="image">Image</label>
                            <input class="form-control" type="file" name="image" id="image">
                        </div>
                        <div class="form-group">
                            <label for="name">Nom</label>
                            <input type="text" class="form-control" name="name" id="name" value="{{ $exercise->name }}">
                        </div>
                        <div class="form-group">
                            <label for="description">Description</label>
                            <textarea class="form-control" name="description" id="description">{{ $exercise->description }}</textarea>
                        </div>
                        <div class="form-group">
                            <label for="level_id">Niveau</label>
                            <select class="form-control" name="level_id" id="level_id">
                                <option value="">----</option>
                                @foreach($levels as $row)
                                    <option value="{{ $row->id }}" {{ $exercise->level_id === $row->id ? 'selected="selected"' : '' }} >{{ $row->name }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-check">
                            <label class="form-check-label">
                                <input type="checkbox" class="form-check-input" name="active" id="active" value="1" {{ $exercise->active ? 'checked="checked"' : '' }} >
                                Active
                            </label>
                        </div>
                        <button type="submit" class="btn btn-primary float-right">Enregistrer</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/exercise/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12 mb-2">
            <a class="btn btn-primary float-right" href="{{route('exercise.create', [$level->id])}}" role="button">Nouveau</a>
        </div>
        <div class="col-md-12">
            <table class="table table-light table-striped">
                <thead class="thead-dark">
                    <tr>
                        <th>Image</th>
                        <th>Nom</th>
                        <th>Description</th>
                        <th>Active</th>
                        <th>Nombre questions</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($exercises as $exercise)
                    <tr>
                        <td class="align-middle"><img style="width:150px;" src="{{asset('storage/'.$exercise->image)}}" class="img-thumbnail" alt="{{$exercise->name}}"></td>
                        <td class="align-middle">{{$exercise->name}}</td>
                        <td class="align-middle"><pre class="mb-0">{{$exercise->description}}</pre></td>
                        <td class="align-middle">{{$exercise->active ? 'Oui' : 'Non'}}</td>
                        <td class="align-middle">{{$exercise->questions->count()}}</td>
                        <td class="text-right align-middle">
                            <a href="{{ route('question.index', [$level->id, $exercise->id]) }}"><i class="fas fa-list-alt"></i></a>
                            <a class="edit-model" href="{{ route('exercise.edit', [$level->id, $exercise->id]) }}"><i class="fas fa-edit"></i></a>
                            <form class="delete-model-form" method="POST" action="{{ route('exercise.destroy', [$level->id, $exercise->id]) }}">
                                @csrf
                                @method('DELETE')
                                <i onclick="deleteModel(event)" class="fas fa-trash-alt delete-model"></i>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection

resources/views/exercise/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <question-component level_id="{{$exercise->level->id}}" exercise_id="{{$exercise->id}}"></question-component>
</div>
@endsection