routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false]);
Route::get('/', 'HomeController@index')->name('home');
Route::get('/start', 'HomeController@start')->name('start');
Route::resource('level', 'LevelController', ['only' => ['show']]);
Route::resource('exercise', 'ExerciseController', ['only' => ['show']]);

Route::prefix('admin')->middleware('auth:web')->group(function () {
    Route::resource('level', 'LevelController', ['except' => ['show']]);
    Route::prefix('level/{level}')->group(function () {
        Route::resource('exercise', 'ExerciseController', ['except' => ['show']]);
        Route::prefix('exercise/{exercise}')->group(function () {
            Route::resource('question', 'QuestionController');
        });
    });
});

app/Level.php
<?php

namespace App;

use App\Exercise;
use Illuminate\Database\Eloquent\Model;

class Level extends Model
{
    protected $guarded = ['id'];

    public function exercises()
    {
        return $this->hasMany(Exercise::class);
    }

    public function scopeActive($query)
    {
        return $query->where('active', true);
    }
}

app/Http/Controllers/LevelController.php
<?php

namespace App\Http\Controllers;

use App\Level;
use App\Http\Requests\RequestLevel;

class LevelController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Support\Facades\View
     */
    public function index()
    {
        $levels = Level::with('exercises')->get();
        return view('level.index', compact('levels'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Support\Facades\View
     */
    public function create()
    {
        return view('level.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\RequestLevel  $request
     * @return \Illuminate\Http\Response
     */
    public function store(RequestLevel $request)
    {
        $level = new Level($request->all());
        $level->save();
        return redirect()->route('level.index')->with(['msg-success' => 'Niveau créé.']);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Level  $level
     * @return \Illuminate\Support\Facades\View
     */
    public function show(Level $level)
    {
        $exercises = $level->exercises;
        return view('level.show', compact('exercises'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Level  $level
     * @return \Illuminate\Support\Facades\View
     */
    public function edit(Level $level)
    {
        return view('level.edit', compact('level'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\RequestLevel  $request
     * @param  \App\Level  $level
     * @return \Illuminate\Http\Response
     */
    public function update(RequestLevel $request, Level $level)
    {
        $request['active'] = isset($request['active']) ?? false;
        $level->update($request->all());
        return redirect()->route('level.index')->with(['msg-success' => 'Niveau mis à jour.']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Level  $level
     * @return \Illuminate\Http\Response
     */
    public function destroy(Level $level)
    {
        $level->delete();
        return redirect()->route('level.index')->with(['msg-success' => 'Niveau supprimé.']);
    }
}

resources/views/level/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <form method="POST" action="{{ route('level.store') }}">
                        @csrf
                        <div class="form-group">
                            <label for="name">Nom</label>
                            <input type="text" class="form-control" name="name" id="name" placeholder="Nom">
                        </div>
                        <div class="form-check">
                            <label class="form-check-label">
                                <input type="checkbox" class="form-check-input" name="active" id="active" value="1" checked>
                                Active
                            </label>
                        </div>
                        <button type="submit" class="btn btn-primary float-right">Enregistrer</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/level/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <form method="POST" action="{{ route('level.update', $level->id) }}">
                        @csrf
                        @method('PATCH')
                        <div class="form-group">
                            <label for="name">Nom</label>
                            <input type="text" class="form-control" name="name" id="name" placeholder="Nom" value="{{ $level->name }}">
                        </div>
                        <div class="form-check">
                            <label class="form-check-label">
                                <input type="checkbox" class="form-check-input" name="active" id="active" value="1" {{ $level->active ? 'checked' : '' }}>
                                Active
                            </label>
                        </div>
                        <button type="submit" class="btn btn-primary float-right">Enregistrer</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/level/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12 mb-2">
            <a class="btn btn-primary float-right" href="{{route('level.create')}}" role="button">Nouveau</a>
        </div>
        <div class="col-md-12">
            <table class="table table-light table-striped">
                <thead class="thead-dark">
                    <tr>
                        <th>Nom</th>
                        <th>Active</th>
                        <th>Nombre exercises</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($levels as $level)
                    <tr>
                        <td scope="row">{{$level->name}}</td>
                        <td>{{$level->active ? 'Oui' : 'Non'}}</td>
                        <td>{{$level->exercises->count()}}</td>
                        <td class="text-right">
                            <a href="{{ route('exercise.index', $level->id) }}"><i class="fab fa-leanpub"></i></a>
                            <a class="edit-model" href="{{ route('level.edit', $level->id) }}"><i class="fas fa-edit"></i></a>
                            <form class="delete-model-form" method="POST" action="{{ route('level.destroy', $level->id) }}">
                                @csrf
                                @method('DELETE')
                                <i onclick="deleteModel(event)" class="fas fa-trash-alt delete-model"></i>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection

resources/views/level/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        
        @foreach ($exercises as $row)
            <div class="col-md-3">
                <div class="card">
                    @if($row->image)
                    <img class="card-img-top" src="{{asset('storage/'.$row->image)}}">
                    @endif
                    <div class="card-body">
                        <h4 class="card-title">{{ $row->name }}</h4>
                        <p class="card-text">{{ $row->description }}</p>
                        <a href="{{route('exercise.show', $row->id)}}" class="btn btn-primary">Go!</a>
                    </div>
                </div>
            </div>
        @endforeach
        
    </div>
</div>
@endsection